Question1(score: 10)

Create a DataFrame from the dictionary and index labels, store it in the variable df.

In [ ]:
import pandas as pd

# Input 
data = {'Artist': ['Ariana Grande', 'Taylor Swift', 'Ed Sheeran', 'Justin Bieber', 'Lady Gaga', 'Bruno Mars'],
        'Genre': ['Jazz', 'Rock', 'Jazz', 'Pop', 'Pop', 'Rock'],
        'Listeners': [1300000, 2700000, 5000000, 2000000, 3000000, 1100000]}

labels = ['AG', 'TS', 'ED', 'JB', 'LG', 'BM']

# Your solution goes here
df = pd.DataFrame(data, index = labels)
df

           Artist Genre  Listeners
AG  Ariana Grande  Jazz    1300000
TS   Taylor Swift  Rock    2700000
ED     Ed Sheeran  Jazz    5000000
JB  Justin Bieber   Pop    2000000
LG      Lady Gaga   Pop    3000000
BM     Bruno Mars  Rock    1100000

Score: 10/10

Excellent!

Question2(score: 10)

a) Select the column labelled “Listeners” and store it in the variable called “col”. 

b) Select the first row and store it in the variable called “row”.

In [ ]:
# Your solution goes here
col = df[["Listeners"]]
row = df.iloc[[0]]
# [df["Listeners"] == 2]

           Artist Genre  Listeners
AG  Ariana Grande  Jazz    1300000

Score: 10/10

Excellent!

Question3(score: 10)

Select all the rows where the Genre is ‘Pop’ and store the result in the variable “pop_artists”.

In [ ]:
# Your solution goes here
pop_artists = df.loc[df["Genre"] == "Pop"]
pop_artists

           Artist Genre  Listeners
JB  Justin Bieber   Pop    2000000
LG      Lady Gaga   Pop    3000000

Score: 10/10

Excellent!

Question4(score: 10)

Select the artists who have more than 2,000,000 listeners and whose Genre is ‘Pop’ and save the output in the variable called “top_pop”.

In [ ]:
# Your solution goes here
top_pop = df.loc[df["Listeners"] > 2000000]
top_pop

          Artist Genre  Listeners
TS  Taylor Swift  Rock    2700000
ED    Ed Sheeran  Jazz    5000000
LG     Lady Gaga   Pop    3000000

In [ ]:
# answer "Pop" singer
top_pop = df[((df['Genre'] == "Pop") & (df['Listeners'] > 2000000))]
top_pop

       Artist Genre  Listeners
LG  Lady Gaga   Pop    3000000

Score: 6/10

Question5(score: 10)

Perform a grouping by Genre using sum() as the aggregation function and store the results in the variable called “grouped”.#

In [ ]:
# Your solution goes here
grouped = df.groupby(['Genre'])[['Listeners']].sum()
grouped

       Listeners
Genre
Jazz     6300000
Pop      5000000
Rock     3800000

In [ ]:
# answer
grouped = df.groupby('Genre').sum()
grouped

       Listeners
Genre
Jazz     6300000
Pop      5000000
Rock     3800000

Score: 10/10

The Listeners selection is not needed.
Excellent